"""
SolutionBank: Manages a per-question collection of reference solutions.

Lifecycle:
1. Pre-training: Load solutions generated by teacher model / hint strategy
   (from data/solutions/*.jsonl)
2. During training: When a generation is scored as correct, add it to the
   bank for that question (up to max_solutions_per_question).
3. Judge query: Retrieve reference solutions for a question to provide
   context for LLM-as-Judge evaluation.

The bank is keyed by question_id (SHA256 hash of question text).
"""

import json
import os
import hashlib
import logging
import threading
from typing import List, Optional, Dict
from collections import OrderedDict

logger = logging.getLogger(__name__)


def make_question_id(question: str) -> str:
    """Deterministic ID for a question."""
    return hashlib.sha256(question.strip().encode()).hexdigest()[:16]


class SolutionBank:
    """Thread-safe solution bank with bounded storage per question.

    Attributes:
        max_solutions: Maximum solutions stored per question.
        bank: {question_id: {"question": str, "ground_truth": str,
                             "solutions": [str, ...]}}
    """

    def __init__(self, max_solutions_per_question: int = 8):
        self.max_solutions = max_solutions_per_question
        self.bank: Dict[str, dict] = {}
        self._lock = threading.Lock()
        self._stats = {"loaded": 0, "added_during_training": 0, "duplicates_skipped": 0}

    # ----- Loading -----

    def load_from_jsonl(self, path: str) -> int:
        """Load pre-generated solutions from a JSONL file.

        Expected format per line:
            {"question_id": "...", "question": "...", "ground_truth": "...",
             "solutions": ["sol1", "sol2", ...]}

        Returns:
            Number of questions loaded.
        """
        if not os.path.exists(path):
            logger.warning(f"Solution file not found: {path}")
            return 0

        count = 0
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    continue

                qid = record.get("question_id", make_question_id(record.get("question", "")))
                solutions = record.get("solutions", [])

                with self._lock:
                    if qid not in self.bank:
                        self.bank[qid] = {
                            "question": record.get("question", ""),
                            "ground_truth": record.get("ground_truth", ""),
                            "solutions": [],
                        }

                    existing = self.bank[qid]["solutions"]
                    for sol in solutions:
                        if len(existing) >= self.max_solutions:
                            break
                        if sol not in existing:
                            existing.append(sol)

                count += 1

        self._stats["loaded"] += count
        logger.info(f"Loaded solutions for {count} questions from {path}")
        return count

    def load_from_directory(self, directory: str) -> int:
        """Load all .jsonl files from a directory."""
        if not os.path.isdir(directory):
            logger.warning(f"Solution directory not found: {directory}")
            return 0

        total = 0
        for fname in sorted(os.listdir(directory)):
            if fname.endswith(".jsonl"):
                total += self.load_from_jsonl(os.path.join(directory, fname))

        logger.info(
            f"SolutionBank: {len(self.bank)} questions, "
            f"{sum(len(v['solutions']) for v in self.bank.values())} total solutions"
        )
        return total

    # ----- Runtime: Add correct solutions during training -----

    def add_solution(
        self,
        question: str,
        solution: str,
        ground_truth: str = "",
    ) -> bool:
        """Add a correct solution discovered during training.

        Returns True if the solution was added (not duplicate, under limit).
        """
        qid = make_question_id(question)

        with self._lock:
            if qid not in self.bank:
                self.bank[qid] = {
                    "question": question,
                    "ground_truth": ground_truth,
                    "solutions": [],
                }

            existing = self.bank[qid]["solutions"]

            # Check capacity
            if len(existing) >= self.max_solutions:
                return False

            # Deduplicate (exact match; could use fuzzy later)
            if solution in existing:
                self._stats["duplicates_skipped"] += 1
                return False

            existing.append(solution)
            self._stats["added_during_training"] += 1
            return True

    def add_correct_generations(
        self,
        questions: List[str],
        responses: List[str],
        rewards: List[float],
        ground_truths: List[str],
        reward_threshold: float = 1.0,
    ) -> int:
        """Batch-add correct generations from a training step.

        Args:
            questions: List of questions.
            responses: List of full response texts.
            rewards: List of outcome rewards (1.0 = correct).
            ground_truths: List of golden answers.
            reward_threshold: Minimum reward to consider "correct".

        Returns:
            Number of solutions added.
        """
        added = 0
        for q, r, score, gt in zip(questions, responses, rewards, ground_truths):
            if score >= reward_threshold:
                if self.add_solution(question=q, solution=r, ground_truth=gt):
                    added += 1
        return added

    # ----- Query -----

    def get_solutions(
        self,
        question: str,
        max_return: Optional[int] = None,
    ) -> List[str]:
        """Get reference solutions for a question.

        Args:
            question: The math problem text.
            max_return: Maximum solutions to return (None = all stored).

        Returns:
            List of solution strings (may be empty).
        """
        qid = make_question_id(question)
        with self._lock:
            entry = self.bank.get(qid)
            if entry is None:
                return []
            solutions = entry["solutions"]
            if max_return is not None:
                return solutions[:max_return]
            return list(solutions)

    def get_ground_truth(self, question: str) -> str:
        """Get the golden answer for a question (if stored)."""
        qid = make_question_id(question)
        with self._lock:
            entry = self.bank.get(qid)
            return entry["ground_truth"] if entry else ""

    def has_solutions(self, question: str) -> bool:
        qid = make_question_id(question)
        with self._lock:
            entry = self.bank.get(qid)
            return entry is not None and len(entry["solutions"]) > 0

    # ----- Persistence -----

    def save_to_jsonl(self, path: str):
        """Save the full bank to a JSONL file."""
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with self._lock:
            with open(path, "w", encoding="utf-8") as f:
                for qid, entry in self.bank.items():
                    record = {
                        "question_id": qid,
                        "question": entry["question"],
                        "ground_truth": entry["ground_truth"],
                        "solutions": entry["solutions"],
                    }
                    f.write(json.dumps(record, ensure_ascii=False) + "\n")
        logger.info(f"Saved solution bank ({len(self.bank)} questions) to {path}")

    # ----- Stats -----

    def get_stats(self) -> dict:
        with self._lock:
            n_questions = len(self.bank)
            n_solutions = sum(len(v["solutions"]) for v in self.bank.values())
            return {
                "n_questions": n_questions,
                "n_solutions": n_solutions,
                "avg_solutions_per_question": n_solutions / max(n_questions, 1),
                **self._stats,
            }

    def __repr__(self):
        stats = self.get_stats()
        return (
            f"SolutionBank(questions={stats['n_questions']}, "
            f"solutions={stats['n_solutions']}, "
            f"max_per_q={self.max_solutions})"
        )
