#!/usr/bin/env bash
# Shared environment setup for all InGPO scripts.
# Source this file at the top of every entry-point script.

set -euo pipefail

# Locate project paths.
INGPO_ROOT="${INGPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
SPO_ROOT="${SPO_ROOT:-${INGPO_ROOT}/spo}"
INGPO_SRC="${INGPO_ROOT}/ingpo_src"

if [[ ! -d "${SPO_ROOT}" ]]; then
  echo "[InGPO] SPO repo missing at ${SPO_ROOT}. Run scripts/setup.sh first." >&2
  exit 1
fi

# PYTHONPATH: SPO src first (so `treetune` is importable), then InGPO ext.
export PYTHONPATH="${SPO_ROOT}/src:${INGPO_SRC}:${PYTHONPATH:-}"

# Make jsonnet `import` resolve in this order:
#   1. InGPO configs/  -- our overrides
#   2. SPO  configs/   -- the inherited SPO library
#   3. SPO root        -- needed because some upstream SPO configs use cwd
#                         relative imports like 'configs/trainers/...' (SPO is
#                         normally launched with cwd=SPO_ROOT).
export APP_JSONNET_PATH="${INGPO_ROOT}/configs:${SPO_ROOT}/configs:${SPO_ROOT}"

# Standard SPO env vars.
export APP_SEED="${APP_SEED:-42}"
export MASTER_PORT="${MASTER_PORT:-$(python3 -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")}"
export APP_DIRECTORY="${APP_DIRECTORY:-${INGPO_ROOT}/experiments}"
export APP_MINIMIZE_STORED_FILES="${APP_MINIMIZE_STORED_FILES:-True}"
export WANDB_PROJECT="${WANDB_PROJECT:-ingpo}"
mkdir -p "${APP_DIRECTORY}"

# Default GPU is index 0; override with INGPO_GPU=N or INGPO_GPUS=0,1,2,3.
# With INGPO_GPUS, Deepspeed launches one process per listed GPU. Episode
# generation is sharded by process, so each rank can host its own vLLM server.
INGPO_GPU_INCLUDE="${INGPO_GPUS:-${INGPO_GPU:-0}}"
INGPO_FIRST_GPU="${INGPO_GPU_INCLUDE%%,*}"

# Ensure the SPO main entrypoint sees both config trees by chaining
# `--configs A,B,C`. We expose helpers for this below.
jsonnet_value() {
  local value="$1"
  case "${value}" in
    auto)
      echo "'auto'"
      ;;
    true|false|null)
      echo "${value}"
      ;;
    *)
      echo "${value}"
      ;;
  esac
}

ensure_gpu_config() {
  local first_gpu="$1"
  local eval_gpu="${INGPO_EVALUATE_GPU:-${first_gpu}}"
  local vllm_gpu_offset="${INGPO_VLLM_GPU_OFFSET:-${first_gpu}}"
  local gen_dir="${APP_DIRECTORY}/_generated_configs/gpus"
  local out="${gen_dir}/gpu_${first_gpu}_eval_${eval_gpu}_vllm_offset_${vllm_gpu_offset}.jsonnet"

  mkdir -p "${gen_dir}"
  cat > "${out}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_gpu_config.
// Deepspeed include: localhost:${INGPO_GPU_INCLUDE}
// Set INGPO_VLLM_GPU_OFFSET to put generation vLLM servers on another GPU block.
{
  evaluate_gpu: ${eval_gpu},
  episode_generator+: {
    gpu_offset: ${vllm_gpu_offset},
  },
}
EOF
  echo "${out}"
}

ensure_runtime_config() {
  if [[ "${INGPO_FAST_OVERLAY:-1}" == "0" ]]; then
    return 0
  fi

  local gen_dir="${APP_DIRECTORY}/_generated_configs/runtime_overrides"
  local out="${gen_dir}/short_run_fast_runtime.jsonnet"

  local eval_every="${INGPO_EVAL_EVERY_N_ITERATIONS:-1000}"
  local save_steps="${INGPO_SAVE_STEPS:-1}"
  local keep_steps="${INGPO_CHECKPOINT_KEEP_STEPS:-1}"
  local vllm_gpu_mem
  vllm_gpu_mem="$(jsonnet_value "${INGPO_VLLM_GPU_MEMORY_UTILIZATION:-auto}")"
  local vllm_min_free="${INGPO_VLLM_MIN_AVAILABLE_GPU_MEMORY_MB:-1024}"
  local max_programs="${INGPO_MAX_CONCURRENT_PROGRAMS:-256}"
  local max_generations="${INGPO_MAX_CONCURRENT_GENERATIONS:-256}"
  local value_max_programs="${INGPO_VALUE_MAX_CONCURRENT_PROGRAMS:-512}"
  local value_max_generations="${INGPO_VALUE_MAX_CONCURRENT_GENERATIONS:-512}"
  local vllm_max_num_seqs="${INGPO_VLLM_MAX_NUM_SEQS:-1024}"
  local vllm_swap_space="${INGPO_VLLM_SWAP_SPACE:-32}"

  mkdir -p "${gen_dir}"
  cat > "${out}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_runtime_config.
// Short-run defaults favor throughput and checkpoint resumability.
// Disable this overlay with INGPO_FAST_OVERLAY=0.
{
  evaluate_every_n_iterations: ${eval_every},
  episode_generator+: {
    vllm_gpu_memory_utilization: ${vllm_gpu_mem},
    vllm_min_available_gpu_memory_mb: ${vllm_min_free},
    inference_strategy+: {
      max_concurrent_programs: ${max_programs},
      max_concurrent_generations: ${max_generations},
    },
    value_estimation_inference_strategy+: {
      max_concurrent_programs: ${value_max_programs},
      max_concurrent_generations: ${value_max_generations},
    },
    vllm_server+: {
      swap_space: ${vllm_swap_space},
      max_num_seqs: ${vllm_max_num_seqs},
      enable_prefix_caching: true,
    },
  },
  trainer+: {
    general_training_args+: {
      save_steps: ${save_steps},
      checkpoint_keep_steps: ${keep_steps},
    },
  },
}
EOF
  echo "${out}"
}

ensure_model_path_config() {
  local model_path="$1"
  if [[ "${model_path}" == *"'"* ]]; then
    echo "[InGPO] MODEL paths containing single quotes are not supported: ${model_path}" >&2
    return 1
  fi

  local safe_name
  safe_name="$(basename "${model_path}" | tr -c 'A-Za-z0-9_.-' '_')"
  local gen_dir="${APP_DIRECTORY}/_generated_configs/models"
  local out="${gen_dir}/model_${safe_name}.jsonnet"

  mkdir -p "${gen_dir}"
  cat > "${out}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_model_path_config.
// Override the base config model alias with a concrete filesystem model path.
local hf_model_name = '${model_path}';

{
  episode_generator+: {
    initial_model_name_or_path: hf_model_name,
    inference_strategy+: {
      guidance_llm+: {
        model: hf_model_name,
      },
    },
    value_estimation_inference_strategy+: {
      guidance_llm+: {
        model: hf_model_name,
      },
    },
  },
  tokenizer+: {
    hf_model_name: hf_model_name,
  },
  trainer+: {
    actor_model+: {
      hf_model_name: hf_model_name,
    },
    reference_model+: {
      hf_model_name: hf_model_name,
    },
  },
}
EOF
  echo "${out}"
}

# Usage: ingpo_run "<exp_name>" "configs/foo.jsonnet,configs/bar.jsonnet" [extra deepspeed args]
ingpo_run() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  local gpu_config runtime_config resolved_cfgs
  gpu_config="$(ensure_gpu_config "${INGPO_FIRST_GPU}")"
  runtime_config="$(ensure_runtime_config)"
  resolved_cfgs="${cfgs},${gpu_config}"
  if [[ -n "${runtime_config}" ]]; then
    resolved_cfgs+=",${runtime_config}"
  fi
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${INGPO_GPU_INCLUDE}" \
    "${INGPO_SRC}/ingpo_main.py" \
    --configs "${resolved_cfgs}" \
    "$@" \
    run_iteration_loop
}

ingpo_eval() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  local last_policy="$1"; shift
  local gpu_config
  gpu_config="$(ensure_gpu_config "${INGPO_FIRST_GPU}")"
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${INGPO_GPU_INCLUDE}" \
    "${INGPO_SRC}/ingpo_main.py" \
    --configs "${cfgs},${gpu_config}" \
    "$@" \
    evaluate --iteration 0 --last_policy_path "${last_policy}"
}
